import psycopg2
import sys
import os
from dotenv import load_dotenv

load_dotenv(".env")
load_dotenv(".env.local")

# Supabase Local Settings
# Default password for local supabase is 'postgres'
DB_HOST = "127.0.0.1"
DB_PORT = "54322"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASS = "postgres"

def init_schema():
    print(f"🔌 Connecting to Local Supabase Postgres ({DB_HOST}:{DB_PORT})...")
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASS
        )
        conn.autocommit = True
        cur = conn.cursor()
        
        print("✅ Connected! Creating tables...")
        
        # 1. Scans Table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS scans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                timestamp TEXT,
                symbol TEXT,
                timeframe TEXT,
                pattern TEXT,
                bias TEXT,
                ai_score REAL,
                ai_reasoning TEXT,
                status TEXT DEFAULT 'PENDING',
                verdict TEXT DEFAULT 'N/A',
                shadow_regime TEXT DEFAULT 'Unknown',
                shadow_multiplier REAL DEFAULT 1.0
            );
        ''')

        # 2. Journal Table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS journal (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                timestamp TEXT,
                trade_id TEXT UNIQUE,
                symbol TEXT,
                side TEXT,
                pnl REAL,
                ai_grade REAL,
                mentor_feedback TEXT,
                deviations TEXT,
                is_lucky_failure BOOLEAN DEFAULT FALSE,
                strategy TEXT DEFAULT 'ROGUE',
                status TEXT DEFAULT 'CLOSED',
                price REAL DEFAULT 0.0,
                notes TEXT
            );
        ''')

        # 3. Sync State Table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS sync_state (
                key TEXT PRIMARY KEY,
                value TEXT,
                last_updated TIMESTAMPTZ DEFAULT NOW()
            );
        ''')

        # 4. System Logs Table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS system_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                timestamp TEXT,
                component TEXT,
                level TEXT,
                message TEXT
            );
        ''')

        # 5. Prop Guardian Audits Table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS prop_guardian_audits (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                timestamp TEXT,
                firm_name TEXT,
                risk_score REAL,
                traps JSONB,
                verdict TEXT,
                recommendation TEXT
            );
        ''')
        
        print("✅ Schema Initialization Complete.")
        
        cur.close()
        conn.close()
        
    except Exception as e:
        print(f"❌ Database Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    init_schema()
