-- Phase 11: SovereignSMC Supabase Schema
-- Run this in your Supabase SQL Editor to initialize the institutional data layer.

-- 1. SCANS TABLE (Intelligent Signals)
CREATE TABLE IF NOT EXISTS scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    timeframe TEXT,
    pattern TEXT,
    bias TEXT,
    ai_score REAL,
    ai_reasoning TEXT,
    status TEXT DEFAULT 'PENDING',
    verdict TEXT DEFAULT 'N/A',
    shadow_regime TEXT DEFAULT 'Unknown',
    shadow_multiplier REAL DEFAULT 1.0
);

-- 2. JOURNAL TABLE (Trade Execution & Audit)
CREATE TABLE IF NOT EXISTS journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    trade_id TEXT UNIQUE NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    pnl REAL DEFAULT 0.0,
    ai_grade REAL DEFAULT 0.0,
    mentor_feedback TEXT,
    deviations TEXT,
    is_lucky_failure BOOLEAN DEFAULT FALSE,
    price REAL DEFAULT 0.0,
    status TEXT DEFAULT 'CLOSED',
    notes TEXT,
    strategy TEXT DEFAULT 'ROGUE'
);

-- 3. PROP GUARDIAN AUDITS (Adversarial Detection)
CREATE TABLE IF NOT EXISTS prop_guardian_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    firm_name TEXT,
    risk_score REAL,
    traps JSONB DEFAULT '[]'::jsonb,
    verdict TEXT,
    recommendation TEXT
);

-- 4. SYSTEM LOGS (Neural Health)
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    component TEXT,
    level TEXT,
    message TEXT
);

-- 5. SYNC STATE (Equity & Daily Stats)
CREATE TABLE IF NOT EXISTS sync_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ENABLE REAL-TIME
-- This allows the dashboard to listen for new rows/updates instantly.
ALTER PUBLICATION supabase_realtime ADD TABLE scans;
ALTER PUBLICATION supabase_realtime ADD TABLE journal;
ALTER PUBLICATION supabase_realtime ADD TABLE prop_guardian_audits;

-- 6. INDEXES for Performance
CREATE INDEX IF NOT EXISTS idx_journal_trade_id ON journal(trade_id);
CREATE INDEX IF NOT EXISTS idx_scans_timestamp ON scans(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_journal_timestamp ON journal(timestamp DESC);
